# Generated by Django 4.1 on 2022-08-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoCareCareers', '0002_jobstatusmodel_jobtypemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=300, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
