# Generated by Django 4.1 on 2022-08-29 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PrecoCareCareers', '0007_jobviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accepted', models.CharField(default='No', max_length=100, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('doctor_licence', models.CharField(max_length=200, null=True)),
                ('exp1_title', models.CharField(max_length=200, null=True)),
                ('exp1_company', models.CharField(max_length=200, null=True)),
                ('exp1_contact', models.CharField(max_length=200, null=True)),
                ('exp2_title', models.CharField(max_length=200, null=True)),
                ('exp2_company', models.CharField(max_length=200, null=True)),
                ('exp2_contact', models.CharField(max_length=200, null=True)),
                ('interview_date1', models.DateField(blank=True, null=True)),
                ('interview_date2', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('User', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userlistings', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='PrecoCareCareers.applicantmodel')),
            ],
        ),
    ]
