# Generated by Django 4.1 on 2022-08-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoCareCareers', '0008_candidatesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesmodel',
            name='listing',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='PrecoCareCareers.joblisting'),
        ),
    ]
