# Generated by Django 4.1 on 2022-08-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoCareCareers', '0009_alter_candidatesmodel_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesmodel',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatesmodel',
            name='admin_creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='PrecoCareCareers.agentmodel'),
        ),
    ]
