# Generated by Django 4.1 on 2022-09-01 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PrecoCareCareers', '0010_candidatesmodel_accepted_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.CharField(default='Favourite', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('User', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favouriteuser', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userfavouritelisting', to='PrecoCareCareers.joblisting')),
            ],
        ),
    ]
