# Generated by Django 4.1 on 2022-09-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoCareCareers', '0011_favouritesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesmodel',
            name='interview_time',
            field=models.CharField(default='No', max_length=100, null=True),
        ),
    ]
