# Generated by Django 4.1 on 2022-09-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoCareCareers', '0012_candidatesmodel_interview_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesmodel',
            name='day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
