# Generated by Django 4.1 on 2022-09-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoCareCareers', '0013_candidatesmodel_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=350, null=True)),
            ],
        ),
    ]
