# Generated by Django 4.1 on 2022-09-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoCareCareers', '0014_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesmodel',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='files/resumes'),
        ),
    ]
